services:
  cache:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379
    volumes:
      - cache:/bitnami/redis/data

volumes:
  cache:
    driver: local